### ISSUE TITLE
brain_extraction_model weight

### ISSUE THREAD

**Issue by slrl123** [alanqrwang/keymorph#10]
hello , where can I found brain_extraction_model.pth.tar?😃

**Comment by is-eyu** [comment]
Hi, thank you for your interest. Please refer to the following ticket, I will update the notebook to include it in the future

https://github.com/alanqrwang/keymorph/issues/9

**Comment by alanqrwang** [comment]
For convenience, I've added the brain extraction model weights to Releases, along with all the other pretrained models: https://github.com/alanqrwang/keymorph/releases/tag/weights.

**Comment by slrl123** [comment]
thanks! that works😁
