### ISSUE TITLE
Cannot find the saved registered image

### ISSUE THREAD

**Issue by steve-zeyu-zhang** [alanqrwang/keymorph#7]
Hi team

I'm using the registering code to register the example data as the instruction

`python register.py \
    --moving ./example_data/images/IXI_001.nii.gz \
    --fixed ./example_data/images/IXI_002.nii.gz \
    --load_path ./weights/numkey512_tps0_dice.4760.h5 \
    --num_keypoints 512 \
    --moving_seg ./example_data/labels/IXI_001.nii.gz \
    --fixed_seg ./example_data/labels/IXI_002.nii.gz `

I've also trigger the ` --save_preds`, but the same, we cannot find the saved registered image. Is there a output folder?

Best,
Zeyu

**Comment by steve-zeyu-zhang** [comment]
Hi team,

I have also tried `--save_dir` configure followed by a `/path/to/output` e.g. `./output`, and still I cannot find any inference image/registered image in the output folder.

Any response?

Thanks,
Steve

**Comment by alanqrwang** [comment]
Apologies for the confusion. It should save to disk now with this commit: https://github.com/alanqrwang/keymorph/commit/7cbdc5492e5bd210a5d95391fcbd30d01dd7d47e.

I updated the README as well. Please let me know if there are any issues.

**Comment by alanqrwang** [comment]
Closing for now. Please feel free to open a separate issue if necessary.
