### ISSUE TITLE
Details about functions.layers.CenterOfMass3d()

### ISSUE THREAD

**Issue by keepgooooing** [alanqrwang/keymorph#8]
Hello! Thanks for your brilliant work! 
I have some questions about the process of centroid calculation：

`        mx = vol.sum(dim=(2,3)) 
        Mx = mx.sum(-1, True) + eps 
        my = vol.sum(dim=(2,4))
        My = my.sum(-1, True) + eps
        mz = vol.sum(dim=(3,4))
        Mz = mz.sum(-1, True) + eps`

Does it mean that the shape of input is [n_batch, channels, dim_Z, dim_Y, dim_X] ?
And what's the difference if I make such changes as below:

`    mx = vol.sum(dim=(3,4)) 
    Mx = mx.sum(-1, True) + eps 
    my = vol.sum(dim=(2,4))
    My = my.sum(-1, True) + eps
    mz = vol.sum(dim=(2,3))
    Mz = mz.sum(-1, True) + eps `

**Comment by alanqrwang** [comment]
Hi, thanks for the question and the positive feedback.

I think this may be a bug in my code... if your input images are not of uniform dimension than the current version of the code will throw an error. I'm working on validating this and will push a commit soon... but in your case I think your version of the code is correct.

**Comment by alanqrwang** [comment]
And yes, you are correct that the input shape is [n_batch, channels, dim_Z, dim_Y, dim_X].

Fixed this in https://github.com/alanqrwang/keymorph/commit/a97413b4330758d63ae71d2b5993e0a1927ab4b8
