### ISSUE TITLE
Weights for brain extraction

### ISSUE THREAD

**Issue by simonoxen** [alanqrwang/keymorph#9]
Hi!, very nice work!

I'm trying to reproduce the preprocessing steps, but I don't seem to find the weights for the brain extraction: `'../weights/brain_extraction_model.pth.tar'`. Are they in the repo? Would it be possible to include them in the release?

Thanks a lot!
Simon

**Comment by is-eyu** [comment]
Hi thanks for your comment, 

Unless @alanqrwang has changed it, the legacy weights for the brain extractor is found in
https://github.com/alanqrwang/keymorph/tree/legacy#decompressing-trained-weights

Best,
Evan

**Comment by simonoxen** [comment]
Great! that works, thanks!
